version: '2'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        volumes:
          - ./data/db:/data/db
        ports:
          - 20002:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
    bot:
        build: .
        depends_on:
          - mongodb
        container_name: "bot"
        volumes:
          - ./config/conf:/conf
        ports:
          - 1202:1202
        entrypoint: "./main -c /conf"